
# Proxima by 64FF00 (xktiverz@gmail.com, @64ff00 for Twitter)

name: Proxima
main: _64FF00\Proxima\Proxima
version: "1.0.0"
api: [2.0.0]
load: STARTUP
author: 64FF00
website: https://github.com/PurePlugins/Proxima
commands:
  proxima:
    description: "/proxima <dpname / ip / port / clisec / uuid / usrname / vwdis>"
permissions:
  proxima:
    description: "Proxima by 64FF00! (Twitter: @64FF00)"
    children:
      proxima.dpname:
        description: "/proxima dpname"
      proxima.ip:
        description: "/proxima ip"
      proxima.clisec:
        description: "/proxima clisec"
      proxima.uuid:
        description: "/proxima uuid"
      proxima.usrname:
        description: "/proxima usrname"
      proxima.vwdis:
        description: "/proxima vwdis"		
